library(shiny)
library(sass)
library(bslib)
library(dplyr)
library(tidyr)
library(tibble)
library(purrr)
library(stringr)
library(bsicons)
library(DT)
library(reactable)
library(htmltools)
library(htmlwidgets)

source("theme.R")
source("prescript.R")
source("ui.R")
source("server.R")

# Run the application 
shinyApp(ui = ui, server = server)
